
BEGIN TRANSACTION;


DROP TABLE IF EXISTS Category;
CREATE TABLE Category (
id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
name VARCHAR (64) NOT NULL
);


DROP TABLE IF EXISTS Course;
CREATE TABLE Course (
id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
id_category INTEGER NOT NULL,
name VARCHAR (64)
);


DROP TABLE IF EXISTS CoursesCategories;
CREATE TABLE CoursesCategories (
id_category INTEGER NOT NULL,
id_course INTEGER NOT NULL,
CONSTRAINT new_pk PRIMARY KEY (id_category, id_course)
);


DROP TABLE IF EXISTS StudentsCourses;
CREATE TABLE StudentsCourses (
id_course INTEGER NOT NULL,
login_student VARCHAR (32) NOT NULL,
CONSTRAINT new_pk PRIMARY KEY (id_course, login_student)
);


DROP TABLE IF EXISTS User;
CREATE TABLE User (
age VARCHAR (32) NOT NULL,
email VARCHAR (64) NOT NULL UNIQUE,
first_name VARCHAR (64) NOT NULL,
id INTEGER NOT NULL UNIQUE PRIMARY KEY AUTOINCREMENT,
last_name VARCHAR (64),
login VARCHAR (32) NOT NULL UNIQUE,
password VARCHAR (8) NOT NULL,
sex VARCHAR (16) NOT NULL DEFAULT 'w',
type_user VARCHAR (28) NOT NULL DEFAULT 'student'
);

COMMIT TRANSACTION;
